In [ ]:
#create a list and array
import numpy as np
list1=[1,2,3]
array1=np.array(list1)
print(list1)
print(array1)

[1, 2, 3]
[1 2 3]


In [21]:
#identify type using type()
import numpy as np
list1=[1,2,3,4]
array1=np.array(list1)
print("list=",list1)
print("array=",array1)
type(list1)
type(array1)


list= [1, 2, 3, 4]
array= [1 2 3 4]


numpy.ndarray

In [11]:
#Perform mathematical operations on these datasets created - multiplication, division,powerof
import numpy as np
array1=np.array([10,20,30])
array2=np.array([2,2,2])
print("array1 * array2=",array1*array2)
print("array1 / array2=",array2/array1)
print("array1 ^ array2=",array2^array1)

array1 * array2= [20 40 60]
array1 / array2= [0.2        0.1        0.06666667]
array1 ^ array2= [ 8 22 28]


In [13]:
# Combine text with Numpy fuction to generate a textual output - ”Addition of Two: array1 +array 2
import numpy as np
array1=np.array([10,20,30])
array2=np.array([2,2,2])
text1="sr"
text2="university"
addition=print("addition of two arrays:",array1+array2)
combined_text=text1+" "+text2
print("combined text:",combined_text)


addition of two arrays: [12 22 32]
combined text: sr university


In [19]:
#Implement np.sin(), log(), log2(), np.exp())
import numpy as np
array1=np.array([10,20,30])
sinarray=np.sin(array1)
logarray=np.log10(array1)
log2array=np.log2(array1)
exparray=np.exp(array1)
print(sinarray)
print(logarray)
print(log2array)
print(exparray)

[-0.54402111  0.91294525 -0.98803162]
[1.         1.30103    1.47712125]
[3.32192809 4.32192809 4.9068906 ]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]


In [22]:
from queue import Queue
 
graph = {0: [1, 3], 1: [0, 2, 3], 2: [4, 1, 5], 3: [4, 0, 1], 4: [2, 3, 5], 5: [4, 2], 6: []}
print("The adjacency List representing the graph is:")
print(graph)
def bfs(graph, source):
    Q = Queue()
    visited_vertices = set()
    Q.put(source)
    visited_vertices.update({0})
    while not Q.empty():
        vertex = Q.get()
        print(vertex, end="-->")
        for u in graph[vertex]:
            if u not in visited_vertices:
                Q.put(u)
                visited_vertices.update({u})
 
print("BFS traversal of graph with source 0 is:")
bfs(graph, 0)

The adjacency List representing the graph is:
{0: [1, 3], 1: [0, 2, 3], 2: [4, 1, 5], 3: [4, 0, 1], 4: [2, 3, 5], 5: [4, 2], 6: []}
BFS traversal of graph with source 0 is:
0-->1-->3-->2-->4-->5-->